### ISSUE TITLE
BSicon MFADEfq.svg does not render correctly

### ISSUE THREAD

**Issue by jc86035** [xingrz/rdt-editor#3]
<img width="142" alt="rdt-editor" src="https://user-images.githubusercontent.com/3948362/74105334-c4d74600-4b54-11ea-861d-fafd1711286a.png">

For some reason rdt-editor renders `MFADEfq` as opaque, when it should be a gradient as shown below.

<img width="105" alt="mw" src="https://user-images.githubusercontent.com/3948362/74105332-c3a61900-4b54-11ea-9a23-081b4f50355e.png">

**Comment by xingrz** [comment]
That's probably the issue of [BSicon_MFADEfq.svg](https://commons.wikimedia.org/wiki/File:BSicon_MFADEfq.svg) itself.

![image](https://user-images.githubusercontent.com/288288/74116336-18e23900-4bee-11ea-89fb-722dd3c4aa2c.png)
The order of these 2 lines should be exchanged.

`rdt-editor` renders icons in pure SVG, instead of the server-side pre-rendered PNGs used by Wikipedia. So any malformed SVGs may be rendered incorrectly by the browser.

I just tried to update the that icon, but the edit privilege of my proxy IP was banned by wikimedia.org (I'm in China where the only way to access Wikipedia is via proxies). Please help me to update. Thanks.
